package compiler

import (
	"fmt"
	"net"
	"strings"

	"github.com/chicohaager/zfw/internal/apps"
)

// The app chains (v1.0.28) hold the answers to the new-app prompt — see
// package apps for the why. Each is a jump target placed in its parent chain
// after every bypass and every user rule, directly before the default-deny
// catch-all:
//
//	DOCKER-USER -> ZFW-APPS     published container ports (IPv4, --ctorigdstport)
//	ZFW-IN      -> ZFW-APPS-IN  network_mode: host apps (IPv4, --dport)
//	ZFW-IN6     -> ZFW-APPS-IN6 IPv6, for ports opened to "any" — on a stock
//	                            ZimaOS an IPv6 connection to a published port
//	                            ends on docker-proxy in INPUT, so this chain
//	                            covers both zones (see dockerUser6Rules)
//
// An apply creates them and the jumps, but never flushes them: both emitters
// use `-N … || true` and the restore documents do not declare them (a
// declared chain is flushed by iptables-restore). Only CompileApps' script,
// run by `zfw apps`, rewrites their content. A user deny for the port sits
// above the jump and therefore always wins.
//
// The target is ACCEPT, not RETURN: a RETURN from the app chain would land
// back in the parent chain and fall straight into the catch-all DROP. In
// DOCKER-USER, ACCEPT skips Docker's own DOCKER chain for that connection;
// for an inbound connection to a published port that chain would accept it
// anyway (it is the port Docker published).
const (
	AppsChainDocker = "ZFW-APPS"
	AppsChainHost   = "ZFW-APPS-IN"
	AppsChainHost6  = "ZFW-APPS-IN6"
)

// appsChainCreate is the idempotent create — never a flush — for one app chain.
func appsChainCreate(ipt, chain string) string {
	return fmt.Sprintf("%s -N %s 2>/dev/null || true\n", ipt, chain)
}

func appsJump(chain string) string { return "-j " + chain }

// AppLines returns the rule bodies for the three app chains.
func AppLines(active []apps.Entry, lan string) (docker, host, host6 []string) {
	// These values end up in a root shell script. apps.json is root-only and
	// written by the daemon, but the check belongs where the value is used.
	if _, _, err := net.ParseCIDR(lan); err != nil {
		lan = ""
	}
	for _, e := range active {
		if (e.Proto != "tcp" && e.Proto != "udp") || e.Port < 1 || e.Port > 65535 {
			continue
		}
		src := ""
		if e.Open() == "lan" {
			if lan == "" {
				continue // no LAN to scope to: stay closed rather than open to all
			}
			src = "-s " + lan + " "
		}
		switch e.Zone {
		case "docker":
			docker = append(docker, fmt.Sprintf("%s-p %s -m conntrack --ctorigdstport %d -j ACCEPT", src, e.Proto, e.Port))
		case "host":
			host = append(host, fmt.Sprintf("%s-p %s --dport %d -j ACCEPT", src, e.Proto, e.Port))
		default:
			continue
		}
		// The LAN is an IPv4 range; only an answer of "any" opens IPv6.
		if e.Open() == "any" {
			host6 = append(host6, fmt.Sprintf("-p %s --dport %d -j ACCEPT", e.Proto, e.Port))
		}
	}
	return docker, host, host6
}

// CompileApps renders the script `zfw apps` runs. It touches nothing but the
// three app chains, and only chains that already exist: before the first
// apply of v1.0.28 there is no jump to them, so content written there would
// be dead anyway — the script says so and leaves the host alone.
func CompileApps(active []apps.Entry, lan string) string {
	docker, host, host6 := AppLines(active, lan)
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by zfwd — DO NOT EDIT. Source of truth: apps.json (new-app prompt)\n")
	b.WriteString("set -eu\n")
	b.WriteString(dockerBackendPick)
	fill := func(ipt, chain string, lines []string) {
		fmt.Fprintf(&b, "if %s -L %s -n >/dev/null 2>&1; then\n", ipt, chain)
		fmt.Fprintf(&b, "  %s -F %s\n", ipt, chain)
		for _, l := range lines {
			fmt.Fprintf(&b, "  %s -A %s %s\n", ipt, chain, l)
		}
		fmt.Fprintf(&b, "  echo \"[zfw] %s: %d\"\n", chain, len(lines))
		b.WriteString("else\n")
		fmt.Fprintf(&b, "  echo \"[zfw] %s missing — apply once to create it\"\n", chain)
		b.WriteString("fi\n")
	}
	fill("$IPT", AppsChainDocker, docker)
	fill("$IPT", AppsChainHost, host)
	b.WriteString(`if [ -n "$IPT6" ]; then` + "\n")
	fill("$IPT6", AppsChainHost6, host6)
	b.WriteString("fi\n")
	return b.String()
}
