package compiler

import (
	"fmt"
	"sort"
	"strings"

	"github.com/chicohaager/zfw/internal/rules"
	"github.com/chicohaager/zfw/internal/system"
)

// CompileRestore is the B4 (v1.1) atomic-apply path: instead of the
// line-by-line `iptables -A` bash script, it emits `iptables-restore`
// table documents so the whole ZFW ruleset for a table is swapped in one
// atomic operation. A malformed ruleset is then rejected wholesale (and
// can be pre-validated with `iptables-restore --test`) instead of
// aborting a bash script half-applied.
//
// Scope of this first cut (offline generator only — NOT wired into the
// engine yet):
//   - V4 carries the IPv4 ZFW chains: ZFW-IN, DOCKER-USER, and the
//     outbound ZFW-OUT / ZFW-FWD-OUT when outbound rules exist.
//   - V6 carries the IPv6 chains: ZFW-IN6 and ZFW-OUT6.
//
// The documents are meant to be applied with `iptables-restore --noflush`
// (and `ip6tables-restore --noflush` for V6): each `:CHAIN - [0:0]` line
// flushes-and-recreates ONLY that ZFW-owned chain, leaving INPUT,
// DOCKER-USER's Docker-managed neighbours, FORWARD and every other chain
// untouched — which is why a full `*filter` replace (that would wipe
// Docker's own chains) is deliberately NOT used.
//
// The chain-jump hooks (`-I INPUT 1 -j ZFW-IN`, etc.), the ipset restore
// and the modprobe preamble are intentionally NOT in these documents:
// they are idempotent / non-atomic shell steps that stay in the engine
// wrapper. The rule *content* here is produced from the same helpers the
// proven bash path uses (hostLines / dockerLines / hostLines6 /
// outboundLines / outboundLines6), and TestRestoreMatchesBashRules pins
// that the per-chain rule sequences are identical to Compile()'s output.
type RestoreScript struct {
	V4 string // iptables-restore --noflush input (filter table)
	V6 string // ip6tables-restore --noflush input (filter table)
}

// CompileRestore builds the restore documents for a rule set. dockerPorts
// resolves zone "auto"; extraBypass appends inbound-bypass interfaces
// (already validated by the caller, as for Compile).
func CompileRestore(rs rules.RuleSet, pp system.PublishedPorts, extraBypass ...string) RestoreScript {
	rl := append([]rules.Rule(nil), rs.Rules...)
	sort.SliceStable(rl, func(i, j int) bool { return rl[i].Order < rl[j].Order })

	return RestoreScript{
		V4: restoreV4(rs, rl, pp, extraBypass),
		V6: restoreV6(rs, rl, pp, extraBypass),
	}
}

// CompileRestoreScript produces the self-contained bash script the engine
// runs in atomic-apply mode (ZFW_APPLY_MODE=restore, B4 / v1.1). Unlike
// the line-by-line Compile() output, the ZFW chains are swapped in via
// iptables-restore, which is atomic per table: a malformed ruleset is
// rejected wholesale instead of aborting half-applied. Each table is
// `--test`'d first so a bad ruleset fails BEFORE the live swap, then
// applied with --noflush so only the ZFW-owned chains are replaced and
// Docker's chains are left intact.
//
// The script keeps the same modprobe + ipset preamble and the same
// idempotent INPUT/OUTPUT/FORWARD jump hooks as the bash path — only the
// chain population changes. It is written alongside compiled.sh; the
// engine picks which one to run, so the bash path stays the default and
// the restore path is opt-in until proven.
func CompileRestoreScript(rs rules.RuleSet, pp system.PublishedPorts, geoFiles map[string]string, extraBypass ...string) string {
	rl := append([]rules.Rule(nil), rs.Rules...)
	sort.SliceStable(rl, func(i, j int) bool { return rl[i].Order < rl[j].Order })
	v4 := restoreV4(rs, rl, pp, extraBypass)
	v6 := restoreV6(rs, rl, pp, extraBypass)
	hasHostOut, hasDockerOut := outboundZones(rl)

	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by zfwd — DO NOT EDIT. Source of truth: rules.json\n")
	b.WriteString("# Atomic-apply variant (B4): ZFW chains are swapped via iptables-restore.\n")
	b.WriteString("set -eu\n")
	// Match the backend Docker uses (nft on ZimaOS>=1.6.2, legacy on <=1.6.1);
	// includes IPTR/IPT6R for the atomic iptables-restore swap.
	b.WriteString(dockerBackendPickRestore)
	b.WriteString("modprobe xt_LOG nf_log_syslog xt_recent xt_time 2>/dev/null || true\n")

	// geo country sets (ipset) — same as the bash path's emitGeoSets.
	if len(geoFiles) > 0 {
		b.WriteString("modprobe ip_set ip_set_hash_net xt_set 2>/dev/null || true\n")
		ccs := make([]string, 0, len(geoFiles))
		for cc := range geoFiles {
			ccs = append(ccs, cc)
		}
		sort.Strings(ccs)
		for _, cc := range ccs {
			f := geoFiles[cc]
			fmt.Fprintf(&b, "[ -r %q ] && ipset restore -exist -f %q\n", f, f)
		}
	}

	// IPv4 filter table — test then atomically swap.
	b.WriteString("\n# ===== IPv4 filter (atomic restore) =====\n")
	b.WriteString(`T4="$(mktemp)"` + "\n")
	b.WriteString("cat > \"$T4\" <<'ZFW_RESTORE_V4'\n")
	b.WriteString(v4)
	b.WriteString("ZFW_RESTORE_V4\n")
	b.WriteString(`"$IPTR" --test --noflush "$T4"` + "\n")
	b.WriteString(`"$IPTR" --noflush "$T4"` + "\n")
	b.WriteString(`rm -f "$T4"` + "\n")

	// IPv6 filter table — only when an ip6tables-restore backend exists.
	b.WriteString("\n# ===== IPv6 filter (atomic restore) =====\n")
	b.WriteString(`if [ -n "$IPT6R" ]; then` + "\n")
	b.WriteString(`  T6="$(mktemp)"` + "\n")
	b.WriteString("  cat > \"$T6\" <<'ZFW_RESTORE_V6'\n")
	b.WriteString(v6)
	b.WriteString("ZFW_RESTORE_V6\n")
	b.WriteString(`  "$IPT6R" --test --noflush "$T6"` + "\n")
	b.WriteString(`  "$IPT6R" --noflush "$T6"` + "\n")
	b.WriteString(`  rm -f "$T6"` + "\n")
	b.WriteString("fi\n")

	// Chain jump hooks — idempotent, identical to the bash path. These
	// stay shell (a -C/-I pair can't live inside a --noflush restore
	// without flushing the built-in chain they hook into).
	b.WriteString("\n# ===== chain jumps (idempotent) =====\n")
	b.WriteString("$IPT -C INPUT -j ZFW-IN 2>/dev/null || $IPT -I INPUT 1 -j ZFW-IN\n")
	b.WriteString(`if [ -n "$IPT6" ]; then $IPT6 -C INPUT -j ZFW-IN6 2>/dev/null || $IPT6 -I INPUT 1 -j ZFW-IN6; fi` + "\n")
	if hasHostOut {
		b.WriteString("$IPT -C OUTPUT -j ZFW-OUT 2>/dev/null || $IPT -I OUTPUT 1 -j ZFW-OUT\n")
		b.WriteString(`if [ -n "$IPT6" ]; then $IPT6 -C OUTPUT -j ZFW-OUT6 2>/dev/null || $IPT6 -I OUTPUT 1 -j ZFW-OUT6; fi` + "\n")
	}
	if hasDockerOut {
		b.WriteString("$IPT -C FORWARD -j ZFW-FWD-OUT 2>/dev/null || $IPT -I FORWARD 1 -j ZFW-FWD-OUT\n")
	}
	return b.String()
}

// restoreV4 emits the IPv4 filter table: ZFW-IN + DOCKER-USER, plus the
// outbound chains when present. Chain declarations precede all -A lines,
// as iptables-restore requires.
func restoreV4(rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) string {
	hasHostOut, hasDockerOut := outboundZones(rl)

	chains := []string{"ZFW-IN", "DOCKER-USER"}
	if hasHostOut {
		chains = append(chains, "ZFW-OUT")
	}
	if hasDockerOut {
		chains = append(chains, "ZFW-FWD-OUT")
	}

	var b strings.Builder
	b.WriteString("*filter\n")
	for _, c := range chains {
		fmt.Fprintf(&b, ":%s - [0:0]\n", c)
	}
	writeChain(&b, "ZFW-IN", zfwInRules(rs, rl, pp.All(), extraBypass))
	writeChain(&b, "DOCKER-USER", dockerUserRules(rs, rl, pp, extraBypass))
	if hasHostOut {
		writeChain(&b, "ZFW-OUT", zfwOutRules(rl))
	}
	if hasDockerOut {
		writeChain(&b, "ZFW-FWD-OUT", zfwFwdOutRules(rl))
	}
	b.WriteString("COMMIT\n")
	return b.String()
}

// restoreV6 emits the IPv6 filter table: ZFW-IN6, plus ZFW-OUT6 when host
// outbound rules exist (the engine wrapper runs this only when an
// ip6tables backend is present).
func restoreV6(rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) string {
	hasHostOut, _ := outboundZones(rl)

	// DOCKER-USER is declared here too: on a host where Docker's ip6tables
	// support is on, the chain already exists (Docker creates it and jumps to
	// it from FORWARD) but is empty. Declaring it is a no-op when Docker's
	// ip6tables support is off — the chain is created, nothing jumps to it.
	chains := []string{"ZFW-IN6", "DOCKER-USER"}
	if hasHostOut {
		chains = append(chains, "ZFW-OUT6")
	}

	var b strings.Builder
	b.WriteString("*filter\n")
	for _, c := range chains {
		fmt.Fprintf(&b, ":%s - [0:0]\n", c)
	}
	writeChain(&b, "ZFW-IN6", zfwIn6Rules(rs, rl, extraBypass))
	writeChain(&b, "DOCKER-USER", dockerUser6Rules(rs, rl, pp, extraBypass))
	if hasHostOut {
		writeChain(&b, "ZFW-OUT6", zfwOut6Rules(rl))
	}
	b.WriteString("COMMIT\n")
	return b.String()
}

func writeChain(b *strings.Builder, chain string, ruleArgs []string) {
	for _, a := range ruleArgs {
		fmt.Fprintf(b, "-A %s %s\n", chain, a)
	}
}

// outboundZones reports whether any enabled outbound rule targets the
// host (ZFW-OUT/ZFW-OUT6) and/or docker (ZFW-FWD-OUT) chains. Mirrors the
// gate in emitOutboundChains.
func outboundZones(rl []rules.Rule) (host, docker bool) {
	for _, r := range rl {
		if !r.Enabled || !r.IsOutbound() {
			continue
		}
		if r.Zone == "host" || r.Zone == "auto" {
			host = true
		}
		if r.Zone == "docker" || r.Zone == "auto" {
			docker = true
		}
	}
	return host, docker
}

// The following *Rules builders return the ordered rule arguments (the
// text after "-A <chain>") for each ZFW chain. They reproduce exactly the
// rule content emitted by the bash path in compiler.go; the static
// bypass/default lines are duplicated here deliberately and pinned
// identical by TestRestoreMatchesBashRules so the two paths cannot drift.

func zfwInRules(rs rules.RuleSet, rl []rules.Rule, dockerPorts map[int]bool, extraBypass []string) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
		"-m conntrack --ctstate INVALID -j DROP",
		"-i lo -j ACCEPT",
		"-i docker0 -j ACCEPT",
		"-i br-+ -j ACCEPT",
		"-i virbr0 -j ACCEPT",
		"-i tailscale0 -j ACCEPT",
		"-i zt+ -j ACCEPT",
		"-i wg+ -j ACCEPT",
		// znet / Zima Net — ZimaOS' own mesh since v1.7.1-beta1 (`znet 0.2.0`, an
		// embedded EasyTier that owns tun0). Same trust level as zt+ above: both
		// are the vendor's remote-access tunnel, authenticated by the mesh itself.
		//
		// Measured 2026-08-14 on a ZimaCube: without this line the desktop client's
		// SYNs to 10.126.126.10:9527 are logged by ZFW-IN-DROP and discarded (125 in
		// one connection attempt), the client hangs on "connecting" forever, and
		// tun0's tx counter sits at 668 bytes for days. Adding it moved tx within
		// two seconds. Listed in BEST-PRACTICES.md and THREAT-MODEL.md.
		"-i tun0 -j ACCEPT",
		"-p icmp -j ACCEPT",
		"-p udp --dport 68 -j ACCEPT",
		"-p udp --dport 41641 -j ACCEPT",
		"-p udp --dport 9993 -j ACCEPT",
	}
	for _, iface := range extraBypass {
		out = append(out, "-i "+iface+" -j ACCEPT")
	}
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		out = append(out, hostLines(r, dockerPorts)...)
	}
	if rs.DefaultPolicy == "allow" {
		out = append(out, "-j RETURN")
	} else {
		out = append(out,
			"-m conntrack --ctstate NEW -j LOG --log-prefix \"ZFW-IN-DROP \" --log-level 6",
			"-j DROP")
	}
	return out
}

// denyLines builds the port-scoped default-deny: a LOG+DROP pair per
// (published port, protocol). conntrack --ctorigdstport is the pre-DNAT
// (published) port and takes a single port only, hence one pair each. NEW-only
// for the same log-volume reason as ZFW-IN.
//
// Both protocols are covered since v1.0.17. Before that only TCP was emitted,
// because the port inventory discarded UDP mappings outright — so a container
// publishing e.g. 8181/udp kept it reachable from any source while its TCP
// sibling was filtered.
func denyLines(pp system.PublishedPorts, logPrefix string) []string {
	ports := make([]int, 0, len(pp.TCP)+len(pp.UDP))
	for p := range pp.All() {
		ports = append(ports, p)
	}
	sort.Ints(ports)

	var out []string
	for _, p := range ports {
		for _, proto := range []string{"tcp", "udp"} {
			if proto == "tcp" && !pp.TCP[p] {
				continue
			}
			if proto == "udp" && !pp.UDP[p] {
				continue
			}
			out = append(out,
				fmt.Sprintf("-p %s -m conntrack --ctorigdstport %d --ctstate NEW -j LOG --log-prefix %q --log-level 6", proto, p, logPrefix),
				fmt.Sprintf("-p %s -m conntrack --ctorigdstport %d --ctstate NEW -j DROP", proto, p))
		}
	}
	return out
}

func dockerUserRules(rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j RETURN",
		"-s 127.0.0.0/8 -j RETURN",
	}
	if rs.HostIP != "" {
		out = append(out, "-s "+rs.HostIP+" -j RETURN")
	}
	out = append(out,
		"-i tailscale0 -j RETURN",
		"-i zt+ -j RETURN",
		"-i wg+ -j RETURN",
		"-i tun0 -j RETURN")
	for _, iface := range extraBypass {
		out = append(out, "-i "+iface+" -j RETURN")
	}
	// Container-originated traffic leaves through the docker bridges, so it is
	// returned BEFORE any user rule is consulted — egress and inter-container
	// flows are none of DOCKER-USER's business here. DOCKER-USER hangs off
	// FORWARD and `--ctorigdstport` carries no direction: for a container's own
	// outbound HTTPS the original destination port is 443, so a user deny rule
	// "any → 443, zone docker" (which the UI presents as an *inbound* rule —
	// outbound has had its own Direction since v0.5.6) matched that egress
	// connection too and killed it. A deny with ports=all went further and cut
	// every container's network access.
	//
	// These two lines used to sit *after* the rule loop, and only under
	// default_policy=deny — while the comment there claimed they were "returned
	// first", which is exactly what they were not. Inbound filtering is
	// unaffected by hoisting them: LAN traffic to a published port arrives on
	// the physical interface, not on docker0/br-+, so it still falls through to
	// the user rules and the per-port default-deny below.
	out = append(out,
		"-i docker0 -j RETURN",
		"-i br-+ -j RETURN")
	all := pp.All()
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		out = append(out, dockerLines(r, all)...)
	}
	if rs.DefaultPolicy == "deny" {
		out = append(out, denyLines(pp, "ZFW-DOCK-DROP ")...)
	}
	out = append(out, "-j RETURN")
	return out
}

// dockerUser6Rules mirrors dockerUserRules onto ip6tables. Docker creates an
// IPv6 DOCKER-USER chain and a FORWARD jump to it whenever its ip6tables
// support is on, but leaves it empty; ZFW never wrote to it before v1.0.17.
//
// On a stock ZimaOS that chain is dead code: Docker publishes no IPv6 DNAT
// rules and containers get no global IPv6 address, so a v6 connection to a
// published port terminates on the host's docker-proxy listener and is
// filtered by ZFW-IN6 in INPUT — it never reaches FORWARD. The moment a user
// enables Docker IPv6 (`"ipv6": true` + fixed-cidr-v6), containers get GUAs,
// v6 traffic is forwarded instead of proxied, and an empty DOCKER-USER means
// every published port is reachable from any IPv6 source. Emit the same
// port-scoped default-deny there so IPv6 cannot be the way in.
//
// 127.0.0.0/8 has no v6 counterpart worth matching (::1 traffic never enters
// FORWARD) and rs.HostIP is IPv4-only, so both are omitted.
func dockerUser6Rules(rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j RETURN",
		"-i tailscale0 -j RETURN",
		"-i zt+ -j RETURN",
		"-i wg+ -j RETURN",
		"-i tun0 -j RETURN",
	}
	for _, iface := range extraBypass {
		out = append(out, "-i "+iface+" -j RETURN")
	}
	all := pp.All()
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		out = append(out, dockerLines6(r, all)...)
	}
	if rs.DefaultPolicy == "deny" {
		out = append(out,
			"-i docker0 -j RETURN",
			"-i br-+ -j RETURN")
		out = append(out, denyLines(pp, "ZFW-DOCK6-DROP ")...)
	}
	out = append(out, "-j RETURN")
	return out
}

func zfwIn6Rules(rs rules.RuleSet, rl []rules.Rule, extraBypass []string) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j RETURN",
		"-m conntrack --ctstate INVALID -j DROP",
		"-i lo -j RETURN",
		"-i docker0 -j RETURN",
		"-i br-+ -j RETURN",
		"-i virbr0 -j RETURN",
		"-i tailscale0 -j RETURN",
		"-i zt+ -j RETURN",
		"-i wg+ -j RETURN",
		"-i tun0 -j RETURN",
	}
	for _, iface := range extraBypass {
		out = append(out, "-i "+iface+" -j RETURN")
	}
	out = append(out,
		"-p ipv6-icmp -j RETURN",
		"-p udp --dport 546 -j RETURN",
		"-s fe80::/10 -j RETURN",
		"-s ff00::/8 -j RETURN")
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		out = append(out, hostLines6(r)...)
	}
	for _, p := range rs.V6Drop {
		out = append(out, fmt.Sprintf("-p tcp --dport %d -j DROP", p))
	}
	if rs.DefaultPolicy == "allow" {
		out = append(out, "-j RETURN")
	} else {
		out = append(out,
			"-m conntrack --ctstate NEW -j LOG --log-prefix \"ZFW-IN6-DROP \" --log-level 6",
			"-j DROP")
	}
	return out
}

func zfwOutRules(rl []rules.Rule) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
		"-o lo -j ACCEPT",
	}
	for _, r := range rl {
		if !r.Enabled || !r.IsOutbound() {
			continue
		}
		if r.Zone != "host" && r.Zone != "auto" {
			continue
		}
		if isIPv6Source(r.Source) {
			continue
		}
		out = append(out, outboundLines(r)...)
	}
	out = append(out, "-j RETURN")
	return out
}

func zfwOut6Rules(rl []rules.Rule) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j RETURN",
		"-o lo -j RETURN",
	}
	for _, r := range rl {
		if !r.Enabled || !r.IsOutbound() {
			continue
		}
		if r.Zone != "host" && r.Zone != "auto" {
			continue
		}
		out = append(out, outboundLines6(r)...)
	}
	out = append(out, "-j RETURN")
	return out
}

func zfwFwdOutRules(rl []rules.Rule) []string {
	out := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j RETURN",
	}
	for _, r := range rl {
		if !r.Enabled || !r.IsOutbound() {
			continue
		}
		if r.Zone != "docker" && r.Zone != "auto" {
			continue
		}
		if isIPv6Source(r.Source) {
			continue
		}
		out = append(out, outboundLines(r)...)
	}
	out = append(out, "-j RETURN")
	return out
}
