// Package compiler turns a rule set into the bash script the ZFW engine
// applies. Each rule becomes iptables commands in ZFW-IN (host-native) and/or
// DOCKER-USER (published container ports); rule order is preserved within
// each chain. Zone "auto" is resolved per port via the dockerPorts map; a
// source of type "country" matches an ipset loaded from geoFiles.
package compiler

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/chicohaager/zfw/internal/geo"
	"github.com/chicohaager/zfw/internal/rules"
	"github.com/chicohaager/zfw/internal/system"
)

// Compile returns the bash ruleset script.
//   - dockerPorts marks which TCP ports are Docker-published (resolves zone "auto").
//   - geoFiles maps a lowercase country code to its ipset-restore file path;
//     these sets are loaded before the rules that reference them.
//   - extraBypass appends additional inbound-bypass interface names to every
//     emitted chain (ZFW-IN, ZFW-IN6, DOCKER-USER). Strings may include the
//     iptables wildcard suffix "+" (e.g. "wg+", "vpn+"). The caller is
//     expected to have validated names — emitting an attacker-controlled
//     iface name here would otherwise be a shell-injection vector via the
//     compiled.sh path. v0.5.4.
func Compile(rs rules.RuleSet, pp system.PublishedPorts, geoFiles map[string]string, extraBypass ...string) string {
	var b strings.Builder
	emitHeader(&b)
	emitGeoSets(&b, geoFiles)

	rl := append([]rules.Rule(nil), rs.Rules...)
	sort.SliceStable(rl, func(i, j int) bool { return rl[i].Order < rl[j].Order })

	// Zone routing keys on the port number alone; only the default-deny needs
	// the protocol split.
	all := pp.All()
	emitHostChain(&b, rs, rl, all, extraBypass)
	emitDockerChain(&b, rs, rl, pp, extraBypass)
	emitV6Chain(&b, rs, rl, all, extraBypass)
	emitDockerChain6(&b, rs, rl, pp, extraBypass)
	emitOutboundChains(&b, rl)
	return b.String()
}

// emitHeader writes the shebang, shell-safety flags and the modprobe of
// the kernel modules every later chain depends on.
// dockerBackendPick emits the shell that selects the iptables backend Docker
// uses (legacy on ZimaOS<=1.6.1, nft on >=1.6.2) by probing which backend owns
// Docker's FORWARD jumps, then falls back to the system default. Emitted into
// both the bash and restore apply paths so a backend switch never leaves ZFW
// writing to an inert table.
// _zfw_fam asks a binary which backend it drives ("nft"/"legacy") instead of
// pattern-matching its name: the fallback path yields the plain `iptables`
// alternatives symlink, which on ZimaOS 1.6.2 drives nf_tables despite having
// no "nft" in its name. The old `case "$IPT" in *nft*)` therefore pinned IPT6
// to ip6tables-legacy and wrote ZFW-IN6 into a table nothing traverses.
const dockerBackendPick = `_zfw_pick_ipt(){ for c in iptables-nft iptables-legacy; do command -v "$c" >/dev/null 2>&1 || continue; if "$c" -S FORWARD 2>/dev/null | grep -qE "DOCKER-USER|DOCKER-FORWARD"; then command -v "$c"; return 0; fi; done; command -v iptables 2>/dev/null || command -v iptables-legacy; }
_zfw_fam(){ "$1" -V 2>/dev/null | grep -q nf_tables && echo nft || echo legacy; }
IPT="$(_zfw_pick_ipt)"
IPTFAM="$(_zfw_fam "$IPT")"
case "$IPTFAM" in nft) IPT6="$(command -v ip6tables-nft 2>/dev/null || command -v ip6tables 2>/dev/null || true)";; *) IPT6="$(command -v ip6tables-legacy 2>/dev/null || command -v ip6tables 2>/dev/null || true)";; esac
`

// dockerBackendPickRestore is dockerBackendPick plus the iptables-restore
// binaries (IPTR/IPT6R) the atomic B4 path needs, kept in the same backend.
const dockerBackendPickRestore = dockerBackendPick + `case "$IPTFAM" in nft) IPTR="$(command -v iptables-nft-restore 2>/dev/null || command -v iptables-restore)"; IPT6R="$(command -v ip6tables-nft-restore 2>/dev/null || command -v ip6tables-restore 2>/dev/null || true)";; *) IPTR="$(command -v iptables-legacy-restore 2>/dev/null || command -v iptables-restore)"; IPT6R="$(command -v ip6tables-legacy-restore 2>/dev/null || command -v ip6tables-restore 2>/dev/null || true)";; esac
`

func emitHeader(b *strings.Builder) {
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by zfwd — DO NOT EDIT. Source of truth: rules.json\n")
	// set -e: a failed iptables line aborts the apply loudly instead of
	// leaving a silently half-applied ruleset (ZFW-7). Every expected-failure
	// line in this script is guarded with `|| true` or sits in an if/&&/||.
	b.WriteString("set -eu\n")
	// Backend selection: match whichever iptables backend Docker actually uses.
	// ZimaOS <=1.6.1 = legacy, >=1.6.2 = nft. Hardcoding legacy silently no-ops
	// after the 1.6.2 nft switch — the rules land in an unused table while the
	// live packet path runs through nft. Detect via Docker's FORWARD jumps.
	b.WriteString(dockerBackendPick)
	// xt_LOG is a module on ZimaOS (not built-in) — load it before the LOG
	// targets below or `-j LOG` errors with "No chain/target/match by that
	// name". nf_log_syslog is its softdep backend (logs to journald/kmsg).
	// xt_limit is NOT shipped on this kernel, so rate-limiting relies on
	// (a) the LOG sitting right before the catch-all DROP — only packets
	// that already failed every allow-rule are logged, and (b) journald's
	// own RateLimitBurst.
	// xt_recent powers per-rule rate-limit (v0.4.4) and xt_time powers
	// time-window rules (v0.4.3). Both are stock kernel modules on
	// modern Linux; modprobe is best-effort so the apply still runs on
	// hosts that built them in (they show as builtin and modprobe
	// becomes a no-op).
	b.WriteString("modprobe xt_LOG nf_log_syslog xt_recent xt_time 2>/dev/null || true\n\n")
}

// emitGeoSets loads the country ipsets referenced by country-source
// rules, sorted for deterministic output. No-op when none are used.
func emitGeoSets(b *strings.Builder, geoFiles map[string]string) {
	if len(geoFiles) == 0 {
		return
	}
	b.WriteString("# ===== geo country sets (ipset) =====\n")
	b.WriteString("modprobe ip_set ip_set_hash_net xt_set 2>/dev/null || true\n")
	ccs := make([]string, 0, len(geoFiles))
	for cc := range geoFiles {
		ccs = append(ccs, cc)
	}
	sort.Strings(ccs)
	for _, cc := range ccs {
		f := geoFiles[cc]
		fmt.Fprintf(b, "[ -r %q ] && ipset restore -exist -f %q\n", f, f)
	}
	b.WriteString("\n")
}

// emitHostChain writes ZFW-IN: the host-native INPUT filter chain.
func emitHostChain(b *strings.Builder, rs rules.RuleSet, rl []rules.Rule, dockerPorts map[int]bool, extraBypass []string) {
	// ---- ZFW-IN: host-native services ----
	b.WriteString("# ===== ZFW-IN (host-native services) =====\n")
	b.WriteString("$IPT -N ZFW-IN 2>/dev/null || true\n")
	b.WriteString("$IPT -F ZFW-IN\n")
	hostBypass := []string{
		"-m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
		"-m conntrack --ctstate INVALID -j DROP",
		"-i lo -j ACCEPT",
		// Container-to-host traffic enters INPUT via the docker bridges, so
		// it must bypass the catch-all DROP or things like a container that
		// resolves mDNS / talks to the host's DNS would be silently blocked.
		// docker0 is the default bridge, br-+ is the wildcard for the
		// user-defined networks Compose creates with names like br-7bf3...
		"-i docker0 -j ACCEPT",
		"-i br-+ -j ACCEPT",
		"-i virbr0 -j ACCEPT",
		"-i tailscale0 -j ACCEPT",
		"-i zt+ -j ACCEPT",
		// WireGuard wildcard — v0.5.4 (the canonical wg0 / wg-clients /
		// wg-mesh setup). Any WireGuard peer that reaches the host on
		// this interface is by definition already authenticated by
		// WireGuard's static-key handshake, so it should be exempt from
		// default-deny the same way tailscale0 already is.
		"-i wg+ -j ACCEPT",
		"-p icmp -j ACCEPT",
		"-p udp --dport 68 -j ACCEPT",
		"-p udp --dport 41641 -j ACCEPT",
		"-p udp --dport 9993 -j ACCEPT",
	}
	for _, iface := range extraBypass {
		hostBypass = append(hostBypass, "-i "+iface+" -j ACCEPT")
	}
	for _, base := range hostBypass {
		fmt.Fprintf(b, "$IPT -A ZFW-IN %s\n", base)
	}
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		for _, line := range hostLines(r, dockerPorts) {
			fmt.Fprintf(b, "$IPT -A ZFW-IN %s\n", line)
		}
	}
	if rs.DefaultPolicy == "allow" {
		b.WriteString("$IPT -A ZFW-IN -j RETURN\n")
	} else {
		// Log the catch-all DROP so the UI's Events tab can show what got
		// blocked. Volume control: only NEW conntrack-state packets are
		// logged (an established connection's later packets would have hit
		// the ESTABLISHED,RELATED ACCEPT at the top of the chain, so by the
		// time a packet reaches here it is almost always a fresh probe).
		b.WriteString("$IPT -A ZFW-IN -m conntrack --ctstate NEW -j LOG --log-prefix \"ZFW-IN-DROP \" --log-level 6\n")
		b.WriteString("$IPT -A ZFW-IN -j DROP\n")
	}
	b.WriteString("$IPT -C INPUT -j ZFW-IN 2>/dev/null || $IPT -I INPUT 1 -j ZFW-IN\n\n")
}

// emitDockerChain writes DOCKER-USER: the published-container-port filter.
// The rule content comes from dockerUserRules so the bash and restore apply
// paths cannot drift (pinned by TestRestoreMatchesBashRules).
func emitDockerChain(b *strings.Builder, rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) {
	b.WriteString("# ===== DOCKER-USER (published container ports) =====\n")
	b.WriteString("if $IPT -L DOCKER-USER -n >/dev/null 2>&1; then\n")
	b.WriteString("  $IPT -F DOCKER-USER\n")
	for _, line := range dockerUserRules(rs, rl, pp, extraBypass) {
		fmt.Fprintf(b, "  $IPT -A DOCKER-USER %s\n", line)
	}
	b.WriteString("fi\n\n")
}

// emitV6Chain writes ZFW-IN6: the IPv6 INPUT filter, always emitted.
func emitV6Chain(b *strings.Builder, rs rules.RuleSet, rl []rules.Rule, dockerPorts map[int]bool, extraBypass []string) {
	// ---- ZFW-IN6: IPv6 INPUT (always emitted) ----
	// ZimaOS ships with SLAAC enabled by default, so a host is reachable on
	// IPv6 the moment a router advertises a prefix. Pre-v0.2.15 we only
	// emitted ZFW-IN6 when the legacy V6Drop blacklist had entries and
	// finished with -j RETURN — i.e. effectively no protection. Now ZFW-IN6
	// mirrors ZFW-IN: always emitted, bypass for trusted interfaces and
	// protocols that IPv6 cannot work without (ICMPv6 for ND/MTU/MLD,
	// DHCPv6 client, link-local fe80::/10, multicast ff00::/8), then the
	// host-zone allow-rules mirrored from the IPv4 chain, and a default-
	// deny with a LOG target so the Events tab can surface IPv6 drops.
	b.WriteString("# ===== ZFW-IN6 (IPv6 INPUT — always emitted from v0.2.15) =====\n")
	b.WriteString(`if [ -n "$IPT6" ]; then` + "\n")
	b.WriteString("  $IPT6 -N ZFW-IN6 2>/dev/null || true\n")
	b.WriteString("  $IPT6 -F ZFW-IN6\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -m conntrack --ctstate INVALID -j DROP\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i lo -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i docker0 -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i br-+ -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i virbr0 -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i tailscale0 -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i zt+ -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -i wg+ -j RETURN\n")
	for _, iface := range extraBypass {
		fmt.Fprintf(b, "  $IPT6 -A ZFW-IN6 -i %s -j RETURN\n", iface)
	}
	// ICMPv6 is non-negotiable on IPv6 — without it Neighbor Discovery,
	// path-MTU and Multicast Listener Discovery all break.
	b.WriteString("  $IPT6 -A ZFW-IN6 -p ipv6-icmp -j RETURN\n")
	// DHCPv6 client (server-to-client port). Harmless if no DHCPv6 is used.
	b.WriteString("  $IPT6 -A ZFW-IN6 -p udp --dport 546 -j RETURN\n")
	// Link-local and multicast addresses: needed for ND, MLD, mDNSv6.
	b.WriteString("  $IPT6 -A ZFW-IN6 -s fe80::/10 -j RETURN\n")
	b.WriteString("  $IPT6 -A ZFW-IN6 -s ff00::/8 -j RETURN\n")
	// Mirror host-zone rules over IPv6. Dispatch by source family:
	//   - "any":      destination-port-only mirror (allow port from any IPv6).
	//   - IPv6 ip/range: -s <addr/cidr> mirrored to ip6tables.
	//   - IPv4 ip/range or country: not mirrored (IPv4 sources can't
	//     express an IPv6 rule; geo-ipsets are IPv4-only). Pre-v0.2.22
	//     an IPv6 ip/range source also crashed the IPv4 chain via a bad
	//     "-s 2001:db8::/64" line — now isIPv6Source() short-circuits.
	for _, r := range rl {
		if !r.Enabled {
			continue
		}
		for _, line := range hostLines6(r, dockerPorts) {
			fmt.Fprintf(b, "  $IPT6 -A ZFW-IN6 %s\n", line)
		}
	}
	// Legacy V6Drop blocklist still honoured for explicit per-port denies
	// (e.g. forbid TCP 5900 on IPv6 even though it might also be in the
	// allow-list). These run before the catch-all so they win.
	for _, p := range rs.V6Drop {
		fmt.Fprintf(b, "  $IPT6 -A ZFW-IN6 -p tcp --dport %d -j DROP\n", p)
	}
	// Default policy. With deny we close the chain with LOG+DROP, matching
	// the IPv4 chain; with allow we just RETURN so any unmatched packet
	// falls back to the system INPUT policy.
	if rs.DefaultPolicy == "allow" {
		b.WriteString("  $IPT6 -A ZFW-IN6 -j RETURN\n")
	} else {
		b.WriteString("  $IPT6 -A ZFW-IN6 -m conntrack --ctstate NEW -j LOG --log-prefix \"ZFW-IN6-DROP \" --log-level 6\n")
		b.WriteString("  $IPT6 -A ZFW-IN6 -j DROP\n")
	}
	b.WriteString("  $IPT6 -C INPUT -j ZFW-IN6 2>/dev/null || $IPT6 -I INPUT 1 -j ZFW-IN6\n")
	b.WriteString("fi\n")
}

// emitDockerChain6 writes the IPv6 DOCKER-USER chain — see dockerUser6Rules
// for why it matters. Guarded twice: no ip6tables backend, or no v6
// DOCKER-USER chain (Docker's ip6tables support off) means nothing to fill.
func emitDockerChain6(b *strings.Builder, rs rules.RuleSet, rl []rules.Rule, pp system.PublishedPorts, extraBypass []string) {
	b.WriteString("\n# ===== DOCKER-USER IPv6 (published container ports) =====\n")
	b.WriteString(`if [ -n "$IPT6" ] && $IPT6 -L DOCKER-USER -n >/dev/null 2>&1; then` + "\n")
	b.WriteString("  $IPT6 -F DOCKER-USER\n")
	for _, line := range dockerUser6Rules(rs, rl, pp, extraBypass) {
		fmt.Fprintf(b, "  $IPT6 -A DOCKER-USER %s\n", line)
	}
	b.WriteString("fi\n")
}

// emitOutboundChains writes ZFW-OUT / ZFW-OUT6 / ZFW-FWD-OUT for
// outbound rules. Entirely skipped when no outbound rules exist, so
// inbound-only deployments compile byte-identically to pre-v0.5.6.
func emitOutboundChains(b *strings.Builder, rl []rules.Rule) {
	// ---- outbound chains (v0.5.6) ----
	// Outbound rules use ZFW-OUT (host) / ZFW-FWD-OUT (docker) / ZFW-OUT6
	// (host IPv6). Unlike inbound, the outbound chains do NOT default-deny —
	// a blanket OUTPUT/FORWARD denial would break the host's own DNS/NTP/
	// container-registry pulls and the Docker gateway. Each outbound rule
	// is targeted; the chain terminates in RETURN. The entire block is
	// skipped when no outbound rules exist, so pre-v0.5.6 inbound-only
	// deployments compile to byte-identical scripts.
	hasHostOut := false
	hasDockerOut := false
	for _, r := range rl {
		if !r.Enabled || !r.IsOutbound() {
			continue
		}
		if r.Zone == "host" || r.Zone == "auto" {
			hasHostOut = true
		}
		if r.Zone == "docker" || r.Zone == "auto" {
			hasDockerOut = true
		}
	}

	if hasHostOut {
		b.WriteString("\n# ===== ZFW-OUT (host-initiated outbound, OUTPUT chain) =====\n")
		b.WriteString("$IPT -N ZFW-OUT 2>/dev/null || true\n")
		b.WriteString("$IPT -F ZFW-OUT\n")
		b.WriteString("$IPT -A ZFW-OUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT\n")
		b.WriteString("$IPT -A ZFW-OUT -o lo -j ACCEPT\n")
		for _, r := range rl {
			if !r.Enabled || !r.IsOutbound() {
				continue
			}
			if r.Zone != "host" && r.Zone != "auto" {
				continue
			}
			if isIPv6Source(r.Source) {
				continue
			}
			for _, line := range outboundLines(r) {
				fmt.Fprintf(b, "$IPT -A ZFW-OUT %s\n", line)
			}
		}
		b.WriteString("$IPT -A ZFW-OUT -j RETURN\n")
		b.WriteString("$IPT -C OUTPUT -j ZFW-OUT 2>/dev/null || $IPT -I OUTPUT 1 -j ZFW-OUT\n")

		// IPv6 mirror — only emitted for host outbound (FORWARD chain in
		// Docker covers v4 + v6 transparently via conntrack).
		b.WriteString(`if [ -n "$IPT6" ]; then` + "\n")
		b.WriteString("  $IPT6 -N ZFW-OUT6 2>/dev/null || true\n")
		b.WriteString("  $IPT6 -F ZFW-OUT6\n")
		b.WriteString("  $IPT6 -A ZFW-OUT6 -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n")
		b.WriteString("  $IPT6 -A ZFW-OUT6 -o lo -j RETURN\n")
		for _, r := range rl {
			if !r.Enabled || !r.IsOutbound() {
				continue
			}
			if r.Zone != "host" && r.Zone != "auto" {
				continue
			}
			for _, line := range outboundLines6(r) {
				fmt.Fprintf(b, "  $IPT6 -A ZFW-OUT6 %s\n", line)
			}
		}
		b.WriteString("  $IPT6 -A ZFW-OUT6 -j RETURN\n")
		b.WriteString("  $IPT6 -C OUTPUT -j ZFW-OUT6 2>/dev/null || $IPT6 -I OUTPUT 1 -j ZFW-OUT6\n")
		b.WriteString("fi\n")
	}

	if hasDockerOut {
		b.WriteString("\n# ===== ZFW-FWD-OUT (container-initiated outbound, FORWARD chain) =====\n")
		b.WriteString("$IPT -N ZFW-FWD-OUT 2>/dev/null || true\n")
		b.WriteString("$IPT -F ZFW-FWD-OUT\n")
		b.WriteString("$IPT -A ZFW-FWD-OUT -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n")
		for _, r := range rl {
			if !r.Enabled || !r.IsOutbound() {
				continue
			}
			if r.Zone != "docker" && r.Zone != "auto" {
				continue
			}
			if isIPv6Source(r.Source) {
				continue
			}
			for _, line := range outboundLines(r) {
				fmt.Fprintf(b, "$IPT -A ZFW-FWD-OUT %s\n", line)
			}
		}
		b.WriteString("$IPT -A ZFW-FWD-OUT -j RETURN\n")
		b.WriteString("$IPT -C FORWARD -j ZFW-FWD-OUT 2>/dev/null || $IPT -I FORWARD 1 -j ZFW-FWD-OUT\n")
	}
}

// outboundLines returns the iptables args (after "-A ZFW-OUT" or
// "-A ZFW-FWD-OUT") for an outbound rule. The Source field is treated
// as the peer (destination from OS perspective) so it's emitted with
// -d rather than -s; the port match still uses --dport because dport
// is always the destination port regardless of direction. Rules with
// no peer source ("any") emit only the port match. Empty result if
// the rule is misshaped for outbound.
//
// The destination address is emitted via strconv.Quote. Be precise about what
// that does and does not buy, because the comment here used to claim more than
// it delivered: strconv.Quote produces a *Go* double-quoted literal, and inside
// bash double quotes `$`, backticks and `\` stay live. It is therefore NOT a
// backstop against shell injection — a value of `$(reboot)` would survive it
// intact into the root-run compiled.sh. It cannot be swapped for POSIX
// single-quoting either: these exact strings are also emitted into the
// iptables-restore document (see compiler_restore.go), whose parser understands
// double quotes and backslash escapes but not single quotes.
//
// So the load-bearing control is rules.Validate, and only rules.Validate: ip and
// range values are canonicalised through net.ParseIP / net.ParseCIDR, which
// cannot return a string containing a shell metacharacter. TestNoShellMetaChar
// CanReachTheCompiler pins that invariant so a future relaxation of Validate
// fails a test instead of quietly opening a root-code-execution path.
func outboundLines(r rules.Rule) []string {
	target := "ACCEPT"
	if r.Action == "deny" {
		target = "DROP"
	}
	sch := scheduleArg(r.Schedule)

	var dst string
	switch r.Source.Type {
	case "any":
		dst = ""
	case "ip", "range":
		dst = "-d " + strconv.Quote(r.Source.Value)
	case "country":
		// Country sources for outbound = "block egress to <country>".
		// Each ipset emits its own line.
		var lines []string
		for _, cc := range rules.SplitCountries(r.Source.Value) {
			match := joinArgs("-m", "set", "--match-set", geo.SetName(cc), "dst", sch)
			lines = append(lines, emitOutboundPortLines(r, match, target)...)
		}
		return lines
	default:
		return nil
	}
	return emitOutboundPortLines(r, joinArgs(dst, sch), target)
}

// outboundLines6 is the IPv6 variant. Only IPv6-source rules emit;
// IPv4 destinations cannot legally match an IPv6 packet. country-
// sources are skipped (no IPv6 geo-ipset support yet).
func outboundLines6(r rules.Rule) []string {
	target := "ACCEPT"
	if r.Action == "deny" {
		target = "DROP"
	}
	sch := scheduleArg(r.Schedule)

	var dst string
	switch r.Source.Type {
	case "any":
		dst = ""
	case "ip", "range":
		if !strings.Contains(r.Source.Value, ":") {
			return nil // IPv4 destination — IPv6 chain skips
		}
		// R4-6: defence-in-depth quoting; see outboundLines comment.
		dst = "-d " + strconv.Quote(r.Source.Value)
	default:
		return nil
	}
	return emitOutboundPortLines(r, joinArgs(dst, sch), target)
}

// emitOutboundPortLines walks the rule's protocol + port selectors and
// returns one wrapEmit'd line per combo. Shared between the v4 and v6
// outbound emitters.
func emitOutboundPortLines(r rules.Rule, baseMatch, target string) []string {
	var lines []string
	switch r.Ports.Type {
	case "all":
		if r.Protocol == "both" {
			lines = append(lines, wrapEmit(baseMatch, r, target)...)
		} else {
			lines = append(lines, wrapEmit(joinArgs(baseMatch, "-p", r.Protocol), r, target)...)
		}
	case "range":
		for _, proto := range protoList(r.Protocol) {
			lines = append(lines, wrapEmit(joinArgs(baseMatch, "-p", proto,
				fmt.Sprintf("--dport %d:%d", r.Ports.From, r.Ports.To)), r, target)...)
		}
	default: // "list"
		for _, proto := range protoList(r.Protocol) {
			for _, pa := range multiport(r.Ports.List) {
				lines = append(lines, wrapEmit(joinArgs(baseMatch, "-p", proto,
					pa), r, target)...)
			}
		}
	}
	return lines
}

// wrapEmit returns the iptables lines for one rule emission point:
// optionally LOG and/or rate-limit lines sharing the match prefix, then
// the action line itself. The match prefix is everything to the right
// of the chain name and to the left of -j — protocol, source, ports,
// schedule, etc. Single-call cohesion keeps host/host6/docker chains
// from drifting on the LOG/rate-limit emit shape.
//
// Round-4 R4-1: defence-in-depth — even though rules.Validate now
// rejects unsafe Rule.ID via isSafeRuleID, the LOG --log-prefix path
// uses strconv.Quote so a future Validate relaxation cannot quietly
// re-open the injection class. The xt_recent --name token has no
// shell metacharacters inside iptables' own parser (it is a single
// `--name <token>` arg) but joinArgs interpolates it as bash, so the
// allowlist on the input side is the load-bearing control.
func wrapEmit(match string, r rules.Rule, target string) []string {
	var out []string
	if r.RateLimit != nil && r.RateLimit.Conn > 0 && r.RateLimit.Seconds > 0 {
		// xt_recent --name has a 32-char cap; isSafeRuleID caps Rule.ID
		// at 16, plus the "z" prefix → max 17. Validate rejects
		// duplicate IDs upstream (R4-5), so two rate-limited rules
		// cannot share a tracking bucket.
		name := "z" + r.ID
		out = append(out,
			joinArgs(match, "-m", "recent", "--set", "--name", name),
			joinArgs(match, "-m", "recent", "--update",
				"--seconds", strconv.Itoa(r.RateLimit.Seconds),
				"--hitcount", strconv.Itoa(r.RateLimit.Conn),
				"--name", name,
				"-j", "DROP"))
	}
	if r.Log {
		out = append(out, joinArgs(match,
			"-j", "LOG",
			"--log-prefix", strconv.Quote("ZFW-RULE-"+r.ID+" "),
			"--log-level", "6"))
	}
	out = append(out, joinArgs(match, "-j", target))
	return out
}

// scheduleArg returns the iptables -m time fragment for a rule's
// schedule, or "" when the rule has no schedule. The kernel time-zone
// is used (--kerneltz) so HH:MM strings represent the host's wall-clock
// rather than UTC — what the user expects from "Allow SSH 08:00-18:00".
// Day names are translated from the lowercase 3-letter form Validate
// accepts (mon/tue/...) to the capitalised form iptables expects
// (Mon/Tue/...). When Days is empty the fragment omits --weekdays
// (every day matches).
func scheduleArg(s *rules.Schedule) string {
	if s == nil {
		return ""
	}
	out := "-m time --timestart " + s.From + " --timestop " + s.To + " --kerneltz"
	if len(s.Days) == 0 {
		return out
	}
	caps := make([]string, 0, len(s.Days))
	for _, d := range s.Days {
		caps = append(caps, scheduleDayMap[strings.ToLower(d)])
	}
	return out + " --weekdays " + strings.Join(caps, ",")
}

// scheduleDayMap turns Validate's lowercase 3-letter day names into the
// capitalised abbreviations iptables-legacy's -m time --weekdays expects.
var scheduleDayMap = map[string]string{
	"mon": "Mon", "tue": "Tue", "wed": "Wed", "thu": "Thu",
	"fri": "Fri", "sat": "Sat", "sun": "Sun",
}

// hostLines6 is the IPv6 variant of hostLines. It returns iptables args
// (after "-A ZFW-IN6") for a rule's host-targeted portion. Source filters
// are applied only when the rule's source is an IPv6 CIDR/IP — IPv4
// sources don't translate. A "country" source is skipped (ipset support
// for IPv6 needs a separate sets, deferred to a later release).
// Outbound rules (v0.5.6) skip this emit entirely.
func hostLines6(r rules.Rule, dockerPorts map[int]bool) []string {
	if r.IsOutbound() {
		return nil
	}
	ps, ok := portsForZone(r, dockerPorts, "host")
	if !ok {
		return nil
	}
	target := "RETURN"
	if r.Action == "deny" {
		target = "DROP"
	}
	src := source6Arg(r.Source)
	if src == "skip" {
		return nil
	}
	sch := scheduleArg(r.Schedule)
	var lines []string
	if ps.All {
		if r.Protocol == "both" {
			lines = append(lines, wrapEmit(joinArgs(src, sch), r, target)...)
		} else {
			lines = append(lines, wrapEmit(joinArgs(src, "-p", r.Protocol, sch), r, target)...)
		}
		return lines
	}
	for _, proto := range protoList(r.Protocol) {
		for _, pa := range portArgs(ps) {
			lines = append(lines, wrapEmit(joinArgs(src, "-p", proto, pa, sch), r, target)...)
		}
	}
	return lines
}

// dockerLines6 is dockerLines for the IPv6 DOCKER-USER chain: same
// published-port (pre-DNAT) conntrack match, but IPv4-only sources — literal
// v4 addresses and the geo ipsets — are skipped, exactly as hostLines6 does.
func dockerLines6(r rules.Rule, dockerPorts map[int]bool) []string {
	if r.IsOutbound() {
		return nil
	}
	ps, ok := portsForZone(r, dockerPorts, "docker")
	if !ok {
		return nil
	}
	src := source6Arg(r.Source)
	if src == "skip" {
		return nil
	}
	target := "RETURN"
	if r.Action == "deny" {
		target = "DROP"
	}
	sch := scheduleArg(r.Schedule)
	var lines []string
	if ps.All {
		if r.Protocol == "both" {
			return wrapEmit(joinArgs(src, sch), r, target)
		}
		return wrapEmit(joinArgs(src, "-p", r.Protocol, sch), r, target)
	}
	for _, proto := range protoList(r.Protocol) {
		if ps.isRange() {
			lines = append(lines, wrapEmit(joinArgs(src, "-p", proto,
				"-m", "conntrack",
				"--ctorigdstport", fmt.Sprintf("%d:%d", ps.From, ps.To),
				sch), r, target)...)
			continue
		}
		for _, p := range ps.List {
			lines = append(lines, wrapEmit(joinArgs(src, "-p", proto,
				"-m", "conntrack", "--ctorigdstport", strconv.Itoa(p),
				sch), r, target)...)
		}
	}
	return lines
}

// source6Arg returns the IPv6 source-match fragment for a rule, or "skip"
// when the rule's source is IPv4-only and therefore cannot be expressed on
// the ip6tables chain.
func source6Arg(s rules.Source) string {
	switch s.Type {
	case "any":
		return ""
	case "ip", "range":
		if strings.Contains(s.Value, ":") {
			return "-s " + s.Value
		}
		return "skip"
	default:
		// country sources need IPv6-specific ipset support — skip for now.
		return "skip"
	}
}

// portSpec is the compiled form of a rule's Ports field — a discriminated
// view that the emitters can switch on without re-reading the source rule.
type portSpec struct {
	All      bool  // every port: emit no --dport clause
	List     []int // multiport list
	From, To int   // inclusive range (when From != 0)
}

func (ps portSpec) isRange() bool { return ps.From != 0 }

// isIPv6Source reports whether a rule's source is an IPv6 address or CIDR.
// IPv6 is detected by the presence of a colon — net.ParseIP/ParseCIDR already
// gated the value through rules.Validate, so a colon is a reliable marker that
// distinguishes IPv6 from IPv4 (which uses dots) or country codes (alpha).
func isIPv6Source(s rules.Source) bool {
	switch s.Type {
	case "ip", "range":
		return strings.Contains(s.Value, ":")
	}
	return false
}

// hostLines returns the iptables args (after "-A ZFW-IN") for a rule's
// host-targeted portion, or nil if the rule does not target the host chain.
// IPv6 sources route to ZFW-IN6 via hostLines6 and must not be emitted here:
// iptables-legacy rejects "-s 2001:db8::/64" and with `set -eu` the whole
// engine script aborts. Pre-v0.2.22 such a rule silently broke every apply.
// Outbound rules (v0.5.6) skip this emit entirely — they belong on
// ZFW-OUT / ZFW-OUT6 / ZFW-FWD-OUT.
func hostLines(r rules.Rule, dockerPorts map[int]bool) []string {
	if r.IsOutbound() {
		return nil
	}
	if isIPv6Source(r.Source) {
		return nil
	}
	ps, ok := portsForZone(r, dockerPorts, "host")
	if !ok {
		return nil
	}
	target := "ACCEPT"
	if r.Action == "deny" {
		target = "DROP"
	}
	sch := scheduleArg(r.Schedule)
	var lines []string
	for _, src := range sourceArgs(r.Source) {
		if ps.All {
			if r.Protocol == "both" {
				lines = append(lines, wrapEmit(joinArgs(src, sch), r, target)...)
			} else {
				lines = append(lines, wrapEmit(joinArgs(src, "-p", r.Protocol, sch), r, target)...)
			}
			continue
		}
		for _, proto := range protoList(r.Protocol) {
			for _, pa := range portArgs(ps) {
				lines = append(lines, wrapEmit(joinArgs(src, "-p", proto, pa, sch), r, target)...)
			}
		}
	}
	return lines
}

// dockerLines returns the iptables args (after "-A DOCKER-USER") for a rule's
// docker-targeted portion. Published ports are matched on the original
// (pre-DNAT) destination port via conntrack. DOCKER-USER lives on the IPv4
// table only; IPv6 sources are skipped here for the same reason as in
// hostLines. Outbound rules (v0.5.6) skip this emit entirely.
func dockerLines(r rules.Rule, dockerPorts map[int]bool) []string {
	if r.IsOutbound() {
		return nil
	}
	if isIPv6Source(r.Source) {
		return nil
	}
	ps, ok := portsForZone(r, dockerPorts, "docker")
	if !ok {
		return nil
	}
	target := "RETURN" // allow: hand back to Docker's accept path
	if r.Action == "deny" {
		target = "DROP"
	}
	sch := scheduleArg(r.Schedule)
	var lines []string
	for _, src := range sourceArgs(r.Source) {
		if ps.All {
			if r.Protocol == "both" {
				lines = append(lines, wrapEmit(joinArgs(src, sch), r, target)...)
			} else {
				lines = append(lines, wrapEmit(joinArgs(src, "-p", r.Protocol, sch), r, target)...)
			}
			continue
		}
		// Container-published ports are matched on the original (pre-DNAT)
		// destination port via conntrack — which accepts both a single port
		// and a "from:to" range expression.
		for _, proto := range protoList(r.Protocol) {
			if ps.isRange() {
				lines = append(lines, wrapEmit(joinArgs(src, "-p", proto,
					"-m", "conntrack",
					"--ctorigdstport", fmt.Sprintf("%d:%d", ps.From, ps.To),
					sch), r, target)...)
				continue
			}
			for _, p := range ps.List {
				lines = append(lines, wrapEmit(joinArgs(src, "-p", proto,
					"-m", "conntrack", "--ctorigdstport", strconv.Itoa(p),
					sch), r, target)...)
			}
		}
	}
	return lines
}

// portArgs renders a portSpec into one or more iptables --dport /
// multiport fragments (multiple when the list exceeds xt_multiport's
// 15-port cap). Caller must not pass an All spec — that case is handled
// earlier.
func portArgs(ps portSpec) []string {
	if ps.isRange() {
		return []string{fmt.Sprintf("--dport %d:%d", ps.From, ps.To)}
	}
	return multiport(ps.List)
}

// portsForZone splits a rule's ports between the host chain and the docker
// chain, honouring rule.Zone (with "auto" resolved per port via dockerPorts).
// A "range" rule always goes to the host chain in auto mode — splitting a
// range across host and docker would lose its single-line iptables form.
func portsForZone(r rules.Rule, dockerPorts map[int]bool, want string) (portSpec, bool) {
	zoned := func(ps portSpec) (portSpec, bool) { return ps, true }
	allSpec := portSpec{All: true}
	listSpec := portSpec{List: r.Ports.List}
	rangeSpec := portSpec{From: r.Ports.From, To: r.Ports.To}

	switch r.Zone {
	case "host":
		if want != "host" {
			return portSpec{}, false
		}
		switch r.Ports.Type {
		case "all":
			return zoned(allSpec)
		case "range":
			return zoned(rangeSpec)
		default:
			return zoned(listSpec)
		}
	case "docker":
		if want != "docker" {
			return portSpec{}, false
		}
		switch r.Ports.Type {
		case "all":
			return zoned(allSpec)
		case "range":
			return zoned(rangeSpec)
		default:
			return zoned(listSpec)
		}
	default: // auto
		if r.Ports.Type == "all" {
			if want == "host" {
				return zoned(allSpec)
			}
			return portSpec{}, false
		}
		if r.Ports.Type == "range" {
			// Auto + range: send the whole range to host (splitting across
			// chains would require multiple range expressions).
			if want == "host" {
				return zoned(rangeSpec)
			}
			return portSpec{}, false
		}
		var hp, dp []int
		for _, p := range r.Ports.List {
			if dockerPorts[p] {
				dp = append(dp, p)
			} else {
				hp = append(hp, p)
			}
		}
		if want == "host" {
			if len(hp) == 0 {
				return portSpec{}, false
			}
			return zoned(portSpec{List: hp})
		}
		if len(dp) == 0 {
			return portSpec{}, false
		}
		return zoned(portSpec{List: dp})
	}
}

// sourceArgs returns the iptables match fragment(s) for a rule's source. A
// country source yields one fragment per country (an ipset match).
func sourceArgs(s rules.Source) []string {
	switch s.Type {
	case "ip", "range":
		return []string{"-s " + s.Value}
	case "country":
		var out []string
		for _, cc := range rules.SplitCountries(s.Value) {
			out = append(out, "-m set --match-set "+geo.SetName(cc)+" src")
		}
		if len(out) == 0 {
			return []string{""}
		}
		return out
	default: // any
		return []string{""}
	}
}

func protoList(p string) []string {
	if p == "both" {
		return []string{"tcp", "udp"}
	}
	return []string{p}
}

// maxMultiportPorts is the kernel xt_multiport limit (XT_MULTI_PORTS):
// at most 15 ports per match. rules.Validate allows up to 128 ports and
// container-binding substitution is uncapped, so longer lists must be
// chunked into one emit per 15 ports — a single over-long line would be
// rejected by iptables and, under the script's set -eu, abort the whole
// apply mid-stream with the chains half-built.
const maxMultiportPorts = 15

func multiport(ports []int) []string {
	var out []string
	for start := 0; start < len(ports); start += maxMultiportPorts {
		end := start + maxMultiportPorts
		if end > len(ports) {
			end = len(ports)
		}
		chunk := ports[start:end]
		if len(chunk) == 1 {
			out = append(out, "--dport "+strconv.Itoa(chunk[0]))
			continue
		}
		ss := make([]string, len(chunk))
		for i, p := range chunk {
			ss[i] = strconv.Itoa(p)
		}
		out = append(out, "-m multiport --dports "+strings.Join(ss, ","))
	}
	return out
}

func joinArgs(parts ...string) string {
	var nn []string
	for _, p := range parts {
		if p != "" {
			nn = append(nn, p)
		}
	}
	return strings.Join(nn, " ")
}
